# export_data.py
# ============================================================
# Data Export Module
# ------------------------------------------------------------
# Saves clean datasets, contaminated datasets, RFI matrix,
# and metadata generated by the signal mixer.
# ============================================================

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


def make_json_serializable(obj: Any) -> Any:
    """
    Convert NumPy/Pandas objects into JSON-serializable Python objects.
    """

    if isinstance(obj, dict):
        return {str(key): make_json_serializable(value) for key, value in obj.items()}

    if isinstance(obj, list):
        return [make_json_serializable(item) for item in obj]

    if isinstance(obj, tuple):
        return [make_json_serializable(item) for item in obj]

    if isinstance(obj, np.ndarray):
        return obj.tolist()

    if isinstance(obj, (np.integer,)):
        return int(obj)

    if isinstance(obj, (np.floating,)):
        return float(obj)

    if isinstance(obj, (np.bool_,)):
        return bool(obj)

    if isinstance(obj, pd.Timestamp):
        return obj.isoformat()

    return obj


def export_mixer_result(
    mixer_result: Any,
    config: dict[str, Any],
    output_prefix: str | None = None,
) -> dict[str, str]:
    """
    Export the output of signal_mixer.mix_clean_with_rfi().

    Parameters
    ----------
    mixer_result:
        MixerResult returned by signal_mixer.py.
    config:
        Validated configuration dictionary.
    output_prefix:
        Optional filename prefix. If None, uses config["run"]["output_prefix"].

    Returns
    -------
    dict
        Dictionary with paths of exported files.
    """

    run_cfg = config.get("run", {})
    export_cfg = config.get("export", {})
    dataset_cfg = config.get("dataset", {})

    output_dir = Path(export_cfg.get("directory", "outputs"))
    output_dir.mkdir(parents=True, exist_ok=True)

    formats = export_cfg.get("formats", {})

    if output_prefix is None:
        output_prefix = str(run_cfg.get("output_prefix", "run_001"))

    exported_files: dict[str, str] = {}

    # --------------------------------------------------------
    # Clean dataset
    # --------------------------------------------------------
    if dataset_cfg.get("save_clean", True) and formats.get("csv", True):
        clean_path = output_dir / f"{output_prefix}_clean.csv"
        mixer_result.clean_df.to_csv(clean_path, index=False)
        exported_files["clean_csv"] = str(clean_path)

    # --------------------------------------------------------
    # Contaminated dataset
    # --------------------------------------------------------
    if dataset_cfg.get("save_contaminated", True) and formats.get("csv", True):
        contaminated_path = output_dir / f"{output_prefix}_contaminated.csv"
        mixer_result.contaminated_df.to_csv(contaminated_path, index=False)
        exported_files["contaminated_csv"] = str(contaminated_path)

    # --------------------------------------------------------
    # RFI matrix as NPY
    # --------------------------------------------------------
    if formats.get("npy", True):
        rfi_path = output_dir / f"{output_prefix}_rfi_matrix.npy"
        np.save(rfi_path, mixer_result.rfi_matrix)
        exported_files["rfi_matrix_npy"] = str(rfi_path)

    # --------------------------------------------------------
    # Metadata JSON
    # --------------------------------------------------------
    if dataset_cfg.get("save_metadata", True) and formats.get("json_metadata", True):
        metadata_path = output_dir / f"{output_prefix}_metadata.json"

        metadata = {
            "dataset_name": dataset_cfg.get("dataset_name", "unnamed_dataset"),
            "output_prefix": output_prefix,
            "channel_columns": mixer_result.channel_cols,
            "channel_freqs_ghz": mixer_result.channel_freqs_ghz,
            "mixer_metadata": mixer_result.metadata,
        }

        metadata = make_json_serializable(metadata)

        with metadata_path.open("w", encoding="utf-8") as f:
            json.dump(metadata, f, indent=2)

        exported_files["metadata_json"] = str(metadata_path)

    return exported_files